-- MySQL Script generated by MySQL Workbench
-- 06/13/17 20:23:38
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sistema_internado
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sistema_internado` ;

-- -----------------------------------------------------
-- Schema sistema_internado
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistema_internado` DEFAULT CHARACTER SET utf8 ;
USE `sistema_internado` ;

-- -----------------------------------------------------
-- Table `sistema_internado`.`salud`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_internado`.`salud` ;

CREATE TABLE IF NOT EXISTS `sistema_internado`.`salud` (
  `id_salud` INT NOT NULL AUTO_INCREMENT,
  `tipo_sangre` VARCHAR(45) NOT NULL,
  `emfermedades` VARCHAR(45) NOT NULL,
  `alergias` VARCHAR(45) NOT NULL,
  `medicamento_toma` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_salud`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_internado`.`carrera`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_internado`.`carrera` ;

CREATE TABLE IF NOT EXISTS `sistema_internado`.`carrera` (
  `id_carrera` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `nivel` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_carrera`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_internado`.`representante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_internado`.`representante` ;

CREATE TABLE IF NOT EXISTS `sistema_internado`.`representante` (
  `id_representante` INT NOT NULL AUTO_INCREMENT,
  `genero` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `estado_civil` VARCHAR(45) NOT NULL,
  `profesion` VARCHAR(45) NOT NULL,
  `ocupacion` VARCHAR(45) NOT NULL,
  `religion` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_representante`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_internado`.`religion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_internado`.`religion` ;

CREATE TABLE IF NOT EXISTS `sistema_internado`.`religion` (
  `id_religion` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `bautizado` VARCHAR(45) NOT NULL,
  `fecha_bautizmo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_religion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_internado`.`login`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_internado`.`login` ;

CREATE TABLE IF NOT EXISTS `sistema_internado`.`login` (
   `id` int(11) NOT NULL,
  `tipo` varchar(45) NOT NULL,
  `fullname` varchar(45) NOT NULL,
  `email` varchar(50) NOT NULL,
  `password` varchar(45) NOT NULL,
  `date` varchar(45) NOT NULL,
  `status` varchar(45) NOT NULL)
ENGINE = InnoDB;


--
-- Volcado de datos para la tabla `login`
--

INSERT INTO `login` (`id`, `tipo`, `fullname`, `email`, `password`, `date`, `status`) VALUES
(1, 'admin', 'Ivan Fernando Paz', 'admin@admin.com', '21232f297a57a5a743894a0e4a801fc3', '', 'activo'),
(2, '', 'Raymond Amangandi', 'raymond.amangandi@itsae.edu.ec', '25d55ad283aa400af464c76d713c07ad', '', '');

-- --------------------------------------------------------

-- -----------------------------------------------------
-- Table `sistema_internado`.`adventistas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_internado`.`adventistas` ;

CREATE TABLE IF NOT EXISTS `sistema_internado`.`adventistas` (
  `id_adventistas` INT NOT NULL AUTO_INCREMENT,
  `iglesia` VARCHAR(45) NOT NULL,
  `distrito` VARCHAR(45) NOT NULL,
  `mision` VARCHAR(45) NOT NULL,
  `cargo` VARCHAR(45) NOT NULL,
  `fami_advenrtista` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_adventistas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_internado`.`estudiantes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_internado`.`estudiantes` ;

CREATE TABLE IF NOT EXISTS `sistema_internado`.`estudiantes` (
  `id_estudiantes` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(50) NOT NULL,
  `apellidos` VARCHAR(50) NOT NULL,
  `sexo` VARCHAR(10) NULL,
  `lugar` TEXT(50) NOT NULL,
  `fech_nacimiento` VARCHAR(45) NOT NULL,
  `cedula` DECIMAL(10,0) NOT NULL,
  `e-mail` VARCHAR(45) NOT NULL,
  `edad` VARCHAR(45) NOT NULL,
  `nacinalidad` VARCHAR(45) NOT NULL,
  `celular` VARCHAR(45) NOT NULL,
  `salud_id_salud` INT NOT NULL,
  `carrera_id_carrera` INT NOT NULL,
  `representante_id_representante` INT NOT NULL,
  `religion_id_religion` INT NOT NULL,
  `login_id_login` INT NOT NULL,
  `adventistas_id_adventistas` INT NOT NULL,
  PRIMARY KEY (`id_estudiantes`),
  CONSTRAINT `fk_estudiantes_salud`
    FOREIGN KEY (`salud_id_salud`)
    REFERENCES `sistema_internado`.`salud` (`id_salud`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estudiantes_carrera1`
    FOREIGN KEY (`carrera_id_carrera`)
    REFERENCES `sistema_internado`.`carrera` (`id_carrera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estudiantes_representante1`
    FOREIGN KEY (`representante_id_representante`)
    REFERENCES `sistema_internado`.`representante` (`id_representante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estudiantes_religion1`
    FOREIGN KEY (`religion_id_religion`)
    REFERENCES `sistema_internado`.`religion` (`id_religion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estudiantes_login1`
    FOREIGN KEY (`login_id_login`)
    REFERENCES `sistema_internado`.`login` (`id_login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estudiantes_adventistas1`
    FOREIGN KEY (`adventistas_id_adventistas`)
    REFERENCES `sistema_internado`.`adventistas` (`id_adventistas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_estudiantes_salud_idx` ON `sistema_internado`.`estudiantes` (`salud_id_salud` ASC);

CREATE INDEX `fk_estudiantes_carrera1_idx` ON `sistema_internado`.`estudiantes` (`carrera_id_carrera` ASC);

CREATE INDEX `fk_estudiantes_representante1_idx` ON `sistema_internado`.`estudiantes` (`representante_id_representante` ASC);

CREATE INDEX `fk_estudiantes_religion1_idx` ON `sistema_internado`.`estudiantes` (`religion_id_religion` ASC);

CREATE INDEX `fk_estudiantes_login1_idx` ON `sistema_internado`.`estudiantes` (`login_id_login` ASC);

CREATE INDEX `fk_estudiantes_adventistas1_idx` ON `sistema_internado`.`estudiantes` (`adventistas_id_adventistas` ASC);


-- -----------------------------------------------------
-- Table `sistema_internado`.`salida`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_internado`.`salida` ;

CREATE TABLE IF NOT EXISTS `sistema_internado`.`salida` (
  `id_salida` INT NOT NULL AUTO_INCREMENT,
  `nombre_u` VARCHAR(45) NOT NULL,
  `motivo_sa` VARCHAR(45) NOT NULL,
  `lugar_destino` VARCHAR(45) NOT NULL,
  `salida` VARCHAR(45) NOT NULL,
  `retorno` VARCHAR(45) NOT NULL,
  `detalles` VARCHAR(1000) NULL,
  `estudiantes_id_estudiantes` INT NOT NULL,
  PRIMARY KEY (`id_salida`),
  CONSTRAINT `fk_salida_estudiantes1`
    FOREIGN KEY (`estudiantes_id_estudiantes`)
    REFERENCES `sistema_internado`.`estudiantes` (`id_estudiantes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_salida_estudiantes1_idx` ON `sistema_internado`.`salida` (`estudiantes_id_estudiantes` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
